### ISSUE TITLE
Express res functions giving an error

### ISSUE THREAD

**Issue by sergiopellegrini** [Chris927/ensure-valid-token-middleware#2]
```
ERR PUT /elections/5c7abb8d0596d00b7184fd3e - 2ms TypeError: res.set is not a function
```

Installed `koa-connect`

```
electionRouter.put(
  '/:electionId',
  c2k(ensureValidToken(RW_SECRET)),
  validator(electionUpdateSchema),
  async (ctx, next) => {
    const { electionId } = ctx.params
    const { body } = ctx.request
    ...
  }
)
```

Versions:
```
{
"koa-connect": "^2.0.1",
"koa": "^2.7.0",
"ensure-valid-token-middleware": "^0.0.3"
}
```

**Comment by Chris927** [comment]
Please try version 0.0.2 of ensure-valid-token-middleware.

Reason: 0.0.3 tries to respond with more detail by setting response headers, via `res.set()`, this may not be compatible with `koa-connect`. This is a wild guess, though.

If this does not resolve it, please provide a stack trace of the error.

**Comment by afrith** [comment]
I believe Chris also fixed this in v0.0.4.

**Comment by Chris927** [comment]
Indeed, thanks @afrith. I can confirm from another project that v0.0.4 is working fine with koa v2.5 (thus most likely on later koa v2 version, too) and koa-connect ^2.0.1.
